### PR TITLE
Handle some simple error conditions better

### PR DESCRIPTION
**Pull request by dsjoerg**
Closing https://github.com/binx/hrc-events/issues/18 and https://github.com/binx/hrc-events/issues/4

### CODE REVIEW

**Comment by binx** [comment]
@dsjoerg in the future, would you mind creating a branch for these PR's so I can test out the code before merging?

**Comment by dsjoerg** [comment]
@binx OK will do

**Comment by dsjoerg** [comment]
@binx once you accept this PR then I'll get my fork synced up with yours and submit a clean PR for the geolocation code I wrote.  I have a PR I could submit now but it confusingly includes other code I've submitted in other PRs.  git drives me nuts!  TT

**Comment by binx** [comment]
@dsjoerg I reworked your error handling and prose to be a bit more consistent with leaflet in https://github.com/binx/hrc-events/pull/23, I'll merge that in and close this one. thanks for catching these bugs!

**Pull request closed without merging**
