### PR TITLE
Swiping!

### PR DESCRIPTION
**Pull request by kielni**
Add swipe controls for details pane on small screens.  Swipe left/right in details pane to show next/previous events.  Highlight marker for currently displayed event.  Tap to close details.  Swipe up/down didn't work for details, because up/down might be needed to scroll content.

### CODE REVIEW

**Comment by kielni** [comment]
for https://github.com/DevProgress/hrc-events/issues/54 and https://github.com/DevProgress/hrc-events/issues/55

**Comment by wboykinm** [comment]
I'm noticing some regressions - should I itemize and start looking for fixes or are you still in-progress on this branch?

**Comment by kielni** [comment]
Yes please; let me know what still needs to be fixed.  I've mostly been testing on Firefox emulator.

**Comment by wboykinm** [comment]
## desktop
- [x] sidebar cards no longer scroll to the right one on map marker click
- [x] clicking on sidebar card no longer pans map/styles selected marker

## mobile
- [x] search doesn't work - `onKeyPress` doesn't fire even with a selection from autocomplete, and  the search button is replaced with a close button
- [x] swipe behavior initially seems to only bring card children in, not parent:

swipe

**Comment by wboykinm** [comment]
Oh man, there's this weird gordian knot of load cards --> swipe card --> taken to new bbox --> cards reshuffled off the target card:

shuffle

**Comment by kielni** [comment]
Hopefully it's all behaving now.

**Comment by wboykinm** [comment]
@kielni That's awesome - desktop is rock-solid (love the active card dashed border) and mobile search is behaving, but still getting the weird card overlaps when swiping:

swipe

At this point the plugin itself might be the problem, which means we should probably skip the swiping behavior altogether and go back to the more-stable map nav. Are you not seeing anything like the above on FF?

**Comment by kielni** [comment]
arrrgh, I could've sworn it was working, but I gave up and switched to https://github.com/thebird/Swipe

I still need to get the detail card to scroll; working on that shortly.

**Comment by wboykinm** [comment]
Woohoo! It's on, with desktop stability retained!

**Pull request merged**
